export const READ_LOG_LIST_REQ = "READ_LOG_LIST_REQ";
export const READ_LOG_LIST_SUCCESS = "READ_LOG_LIST_SUCCESS";
export const READ_LOG_LIST_FAIL = "READ_LOG_LIST_FAIL";

export const READ_LOG_INFO_REQ = "READ_LOG_INFO_REQ";
export const READ_LOG_INFO_SUCCESS = "READ_LOG_INFO_SUCCESS";
export const READ_LOG_INFO_FAIL = "READ_LOG_INFO_FAIL";

export const READ_LOG_CREATE_REQ = "READ_LOG_CREATE_REQ";
export const READ_LOG_CREATE_SUCCESS = "READ_LOG_CREATE_SUCCESS";
export const READ_LOG_CREATE_FAIL = "READ_LOG_CREATE_FAIL";

export const READ_LOG_UPDATE_REQ = "READ_LOG_UPDATE_REQ";
export const READ_LOG_UPDATE_SUCCESS = "READ_LOG_UPDATE_SUCCESS";
export const READ_LOG_UPDATE_FAIL = "READ_LOG_UPDATE_FAIL";

export const READ_LOG_DELETE_REQ = "READ_LOG_DELETE_REQ";
export const READ_LOG_DELETE_SUCCESS = "READ_LOG_DELETE_SUCCESS";
export const READ_LOG_DELETE_FAIL = "READ_LOG_DELETE_FAIL";